<?php

return [
    'id' => 'hawk',
    'type' => 'monster',
    'is_player' => false,
    'name' => 'Hawk',
    'display_name' => 'Hawk',
    'role' => 'Monster',
    'element' => 'neutral',
    'desc' => 'A swift and agile bird of prey. Hawks strike from above with sharp talons and keen eyesight, making them excellent ranged attackers.',
    'base_level' => 3,
    'images' => [
        'default' => 'assets/entities/hawk/avatar.webp',
    ],
    'animations' => [
        'base' => 'entities',
        'types' => ['idle'],
        'idle'  => ['animationFPS' => 12, 'animationScale' => 1.4, 'animationOffsetX' => -2, 'animationOffsetXWhenFacingRight' => 2,  'animationOffsetY' => 30],
    ],
    'sounds' => [
        'death' => ['monster_death1', 'monster_death2'],
    ],
    'growth' => [
        'hp_base_per_level' => 15,
        'hp_vit_mult'       => 3,
        'sp_base_per_level' => 10,
        'sp_int_mult'       => 3,
        'atk_base'          => 15,
        'atk_str_mult'      => 0.5,
        'atk_dex_mult'      => 2.5,
        'atk_lvl_mult'      => 1.5,
    ],
    'attributes' => [
        'str' => 5,
        'agi' => 14,
        'vit' => 5,
        'int' => 3,
        'dex' => 12,
        'luk' => 6,
    ],
    'maxHp' => 30,
    'maxSp' => 60,
    'attack' => 7,
    'defense' => 2,
    'moveRange' => 4,
    'attackRange' => 3,
    'behavior' => 'aggressive',
    'scale' => 1.0,
    'attacks' => 1,
    'skills' => [
        [
            'id' => 'talon_strike',
            'name' => 'Talon Strike',
            'mana' => 6,
            'dmg_mult' => 0.9,
            'icon' => 'crosshair',
            'type' => 'single',
            'range' => 3,
            'description' => 'A swift talon strike from above.',
        ],
        [
            'id' => 'dive_bomb',
            'name' => 'Dive Bomb',
            'mana' => 10,
            'dmg_mult' => 1.1,
            'icon' => 'arrow-down',
            'type' => 'single',
            'range' => 4,
            'description' => 'Dives down to strike the target with increased damage.',
        ],
    ],
    'loot_table' => [
        'gold_min' => 8,
        'gold_max' => 12,
        'xp' => 10,
        'items' => [
            ['id' => 'hawk_feather', 'chance' => 0.7, 'rarity' => 'common'],
            ['id' => 'sharp_talon', 'chance' => 0.4, 'rarity' => 'common'],
        ],
    ],
];
