<?php

return [
    'id' => 'toxic_slime',
    'type' => 'monster',
    'is_player' => false,
    'name' => 'Toxic Slime',
    'display_name' => 'Toxic Slime',
    'role' => 'Monster',
    'element' => 'poison',
    'desc' => 'A poisonous slime creature that oozes through dark places. Their toxic touch can dissolve flesh and spread disease to those unfortunate enough to encounter them.',
    'base_level' => 5,
    'images' => [
        'default' => 'assets/entities/toxic_slime/avatar.webp',
    ],
    'animations' => [
        'base' => 'entities',
        'types' => ['idle'],
        'idle'  => ['animationFPS' => 12, 'animationScale' => 0.7, 'animationOffsetX' => 1, 'animationOffsetXWhenFacingRight' => -1, 'animationOffsetY' => 39],
    ],
    'sounds' => [
        'death' => ['monster_death1', 'monster_death2'],
        'idle' => ['slime'],
    ],
    'attributes' => [
        'str' => 8,
        'agi' => 3,
        'vit' => 12,
        'int' => 6,
        'dex' => 3,
        'luk' => 5,
    ],
    'maxHp' => 30,
    'maxSp' => 50,
    'attack' => 8,
    'defense' => 2,
    'moveRange' => 2,
    'attackRange' => 1,
    'behavior' => 'aggressive',
    'scale' => 1.0,
    'attacks' => 1,
    'skills' => [
        [
            'id' => 'dissolve',
            'name' => 'Dissolve',
            'mana' => 10,
            'dmg_mult' => 0.8,
            'icon' => 'poison',
            'type' => 'single',
            'description' => 'A toxic attack that dissolves flesh.',
            'effect' => ['id' => 'poison', 'chance' => 0.3, 'duration' => 2],
        ],
        [
            'id' => 'bounce',
            'name' => 'Bounce',
            'mana' => 5,
            'dmg_mult' => 0.5,
            'icon' => 'bounce',
            'type' => 'single',
            'description' => 'A quick bouncing attack.',
        ],
        [
            'id' => 'slime_split',
            'name' => 'Slime Split',
            'mana' => 15,
            'dmg_mult' => 0.6,
            'icon' => 'split',
            'type' => 'aoe',
            'description' => 'Splits into multiple attacks.',
        ],
        [
            'id' => 'toxic_spit',
            'name' => 'Toxic Spit',
            'mana' => 12,
            'dmg_mult' => 1.0,
            'icon' => 'poison',
            'type' => 'single',
            'description' => 'Spits toxic venom at target.',
            'effect' => ['id' => 'poison', 'chance' => 0.5, 'duration' => 2],
        ],
    ],
    'loot_table' => [
        'gold_min' => 5,
        'gold_max' => 8,
        'xp' => 8,
        'items' => [
            ['id' => 'slime_gel', 'chance' => 0.7, 'rarity' => 'common'],
            ['id' => 'poison_sac', 'chance' => 0.2, 'rarity' => 'uncommon'],
        ],
    ],
];
