<?php

return [
    'id' => 'wolf',
    'type' => 'monster',
    'is_player' => false,
    'name' => 'Dire Wolf',
    'display_name' => 'Dire Wolf',
    'role' => 'Monster',
    'element' => 'neutral',
    'desc' => 'A fierce and intelligent wolf that hunts in packs. Known for their savage bites and coordinated attacks, they are dangerous predators of the wilderness.',
    'base_level' => 5,
    'images' => [
        'default' => 'assets/entities/wolf/avatar.webp',
    ],
    'animations' => [
        'base' => 'entities',
        'types' => ['idle', 'walk', 'atack'],
        'idle'  => ['animationFPS' => 10,   'animationScale' => 1.6, 'animationOffsetX' => -1, 'animationOffsetXWhenFacingRight' => 1,  'animationOffsetY' => 36],
        'walk'  => ['animationFPS' => 13,   'animationScale' => 1.8, 'animationOffsetX' => 0,  'animationOffsetXWhenFacingRight' => 0,  'animationOffsetY' => 36],
        'atack' => ['animationFPS' => 14.5, 'animationScale' => 0.9, 'animationOffsetX' => 3,  'animationOffsetXWhenFacingRight' => -3, 'animationOffsetY' => 45],
    ],
    'sounds' => [
        'hit' => ['wolf_claw_hit1', 'wolf_claw_hit2', 'wolf_claw_hit3', 'wolf_claw_hit4'],
        'death' => ['monster_death1', 'monster_death2'],
        'skill_special' => ['howling_wolf'],
    ],
    'attributes' => [
        'str' => 8,
        'agi' => 10,
        'vit' => 8,
        'int' => 2,
        'dex' => 8,
        'luk' => 3,
    ],
    'maxHp' => 40,
    'maxSp' => 90,
    'attack' => 9,
    'defense' => 4,
    'moveRange' => 4,
    'attackRange' => 1,
    'behavior' => 'aggressive',
    'scale' => 1.0,
    'attacks' => 1,
    'skills' => [
        [
            'id' => 'savage_bite',
            'name' => 'Savage Bite',
            'mana' => 8,
            'dmg_mult' => 1.0,
            'icon' => 'bite',
            'type' => 'single',
            'description' => 'A savage bite attack.',
            'effect' => ['id' => 'bleed', 'chance' => 0.2, 'duration' => 2],
        ],
        [
            'id' => 'lunge',
            'name' => 'Lunge',
            'mana' => 10,
            'dmg_mult' => 0.9,
            'icon' => 'lunge',
            'type' => 'single',
            'range' => 2,
            'description' => 'Lunges forward to attack from distance.',
        ],
    ],
    'loot_table' => [
        'gold_min' => 12,
        'gold_max' => 15,
        'xp' => 15,
        'items' => [
            ['id' => 'wolf_fang', 'chance' => 0.8, 'rarity' => 'common'],
            ['id' => 'wolf_pelt', 'chance' => 0.5, 'rarity' => 'common'],
            ['id' => 'moonstone', 'chance' => 0.15, 'rarity' => 'uncommon'],
        ],
    ],
];
