<?php

$sql = <<<SQL
CREATE TABLE IF NOT EXISTS characters (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(50) NOT NULL,
    class ENUM('Espadachim', 'Arqueiro', 'Mago', 'Ladrão', 'Acolito', 'Ferreiro') NOT NULL,
    gender ENUM('male', 'female') NOT NULL DEFAULT 'male',
    level INT UNSIGNED NOT NULL DEFAULT 1,
    str INT UNSIGNED NOT NULL DEFAULT 10,
    agi INT UNSIGNED NOT NULL DEFAULT 10,
    vit INT UNSIGNED NOT NULL DEFAULT 10,
    `int` INT UNSIGNED NOT NULL DEFAULT 10,
    dex INT UNSIGNED NOT NULL DEFAULT 10,
    luk INT UNSIGNED NOT NULL DEFAULT 10,
    hp INT UNSIGNED NOT NULL DEFAULT 100,
    max_hp INT UNSIGNED NOT NULL DEFAULT 100,
    mana INT UNSIGNED NOT NULL DEFAULT 50,
    max_mana INT UNSIGNED NOT NULL DEFAULT 50,
    xp INT UNSIGNED NOT NULL DEFAULT 0,
    gold INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_uuid (uuid),
    INDEX idx_user_id (user_id),
    INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SQL;

