<?php

return [
    'id' => 'acolyte',
    'type' => 'class',
    'is_player' => true,
    'name' => 'Acolyte',
    'display_name' => 'Acolyte',
    'role' => 'Support',
    'element' => 'holy',
    'desc' => 'A sacred cleric devoted to divine powers of healing and protection. They channel holy energy to mend wounds, shield allies, and smite the unholy.',
    'base_level' => 1,
    'images' => [
        'default' => 'assets/entities/acolyte/avatar.webp',
        'male' => 'assets/img/sacer-male.webp',
        'female' => 'assets/img/sacer-female.webp',
    ],
    'animations' => [
        'base' => 'entities',
        'types' => ['idle', 'walk', 'atack'],
        'idle'  => ['animationFPS' => 12.5, 'animationScale' => 1.2, 'animationOffsetX' => -8, 'animationOffsetXWhenFacingRight' => 8,  'animationOffsetY' => 34],
        'walk'  => ['animationFPS' => 9,    'animationScale' => 1.5, 'animationOffsetX' => -6, 'animationOffsetXWhenFacingRight' => 6,  'animationOffsetY' => 39],
        'atack' => ['animationFPS' => 14,   'animationScale' => 2,   'animationOffsetX' => 0,  'animationOffsetXWhenFacingRight' => 0,  'animationOffsetY' => 50],
    ],
    'sounds' => [
        'weapon' => 'staff',
        'skill_start' => ['acolyte_skill_prepare', 'acolyte_skill_prepare2', 'acolyte_skill_prepare3', 'acolyte_skill_prepare4'],
        'hit' => ['staff_hit', 'staff_hit2', 'staff_hit3'],
        'attack_prepare' => ['staff_prepare1', 'staff_prepare2'],
        'death' => ['hero_death'],
        'buff_apply' => ['buff_apply1', 'buff_apply2', 'buff_apply3'],
        'debuff_apply' => ['debuff_apply'],
    ],
    'attributes' => [
        'str' => 5,
        'agi' => 6,
        'vit' => 7,
        'int' => 14,
        'dex' => 7,
        'luk' => 6,
    ],
    'maxHp' => 70,
    'maxSp' => 140,
    'attack' => 6,
    'defense' => 3,
    'moveRange' => 3,
    'attackRange' => 1,
    'scale' => 1.6,
    'skills' => [
        [
            'id' => 'heal',
            'name' => 'Heal',
            'mana' => 30,
            'dmg_mult' => 0,
            'healPct' => 0.35,
            'healMatk' => 0.6,
            'power' => 0,
            'icon' => 'heart',
            'type' => 'heal',
            'range' => 4,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'description' => 'Restores 35% of target max HP plus bonus from INT/MATK.',
        ],
        [
            'id' => 'bless',
            'name' => 'Bless',
            'mana' => 25,
            'dmg_mult' => 0,
            'icon' => 'sun',
            'type' => 'ally',
            'range' => 4,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'description' => 'Increases DEF and reduces damage taken for 2 turns.',
            'buff' => [
                'id' => 'bless',
                'damageTaken' => 0.85,
                'duration' => 2,
            ],
        ],
        [
            'id' => 'smite',
            'name' => 'Smite',
            'mana' => 15,
            'dmg_mult' => 0.9,
            'icon' => 'sun',
            'type' => 'single',
            'range' => 3,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'element' => 'holy',
            'description' => 'A holy bolt that smites an enemy.',
        ],
        [
            'id' => 'holy_weaken',
            'name' => 'Holy Weaken',
            'mana' => 20,
            'dmg_mult' => 0.5,
            'icon' => 'shield',
            'type' => 'single',
            'range' => 3,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'element' => 'holy',
            'description' => 'Weakens an enemy, reducing their speed.',
            'effect' => ['id' => 'slow', 'chance' => 0.8, 'duration' => 2],
        ],
        [
            'id' => 'sanctuary',
            'name' => 'Sanctuary',
            'mana' => 50,
            'dmg_mult' => 0,
            'healPct' => 0.22,
            'healMatk' => 0.35,
            'power' => 0,
            'icon' => 'heart',
            'type' => 'aoe_heal',
            'range' => 0,
            'rangeType' => 'aoe',
            'aoe' => 0,
            'gridVisual' => 'aoe_heal',
            'description' => 'Heals all allies for 22% of their max HP plus bonus from INT/MATK.',
        ],
    ],
];
