<?php

return [
    'id' => 'archer',
    'type' => 'class',
    'is_player' => true,
    'name' => 'Archer',
    'display_name' => 'Archer',
    'role' => 'Ranged',
    'element' => 'neutral',
    'desc' => 'A precision archer with deep connection to nature and keen eyesight. They strike from a distance with deadly accuracy, using the environment to their advantage.',
    'base_level' => 1,
    'images' => [
        'default' => 'assets/entities/archer/avatar.webp',
    ],
    'animations' => [
        'base' => 'entities',
        'types' => ['idle', 'walk', 'atack'],
        'idle'  => ['animationFPS' => 17.5, 'animationScale' => 1.4, 'animationOffsetX' => -5, 'animationOffsetXWhenFacingRight' => 5,  'animationOffsetY' => 35],
        'walk'  => ['animationFPS' => 9.5,  'animationScale' => 1.6, 'animationOffsetX' => -8, 'animationOffsetXWhenFacingRight' => 8,  'animationOffsetY' => 33],
        'atack' => ['animationFPS' => 14.5, 'animationScale' => 1.4, 'animationOffsetX' => -3, 'animationOffsetXWhenFacingRight' => 3,  'animationOffsetY' => 36],
    ],
    'sounds' => [
        'weapon' => 'bow',
        'skill_start' => ['archer_skill_start1', 'archer_skill_start2', 'archer_skill_start3'],
        'hit' => ['bow1', 'bow2', 'bow3'],
        'attack_prepare' => ['bow1', 'bow2', 'bow3'],
        'death' => ['hero_death'],
        'damage_taken' => ['damage_taken1', 'damage_taken2', 'damage_taken3', 'damage_taken4'],
        'crit' => ['critical'],
        'buff_apply' => ['buff_apply1', 'buff_apply2', 'buff_apply3'],
        'debuff_apply' => ['debuff_apply'],
    ],
    'attributes' => [
        'str' => 8,
        'agi' => 16,
        'vit' => 8,
        'int' => 7,
        'dex' => 18,
        'luk' => 7,
    ],
    'maxHp' => 80,
    'maxSp' => 150,
    'attack' => 12,
    'defense' => 4,
    'moveRange' => 4,
    'attackRange' => 3,
    'scale' => 1.7,
    'skills' => [
        [
            'id' => 'quick_shot',
            'name' => 'Quick Shot',
            'mana' => 5,
            'dmg_mult' => 1.0,
            'icon' => 'crosshair',
            'type' => 'single',
            'range' => 4,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'description' => 'Basic ranged attack against a single target.',
        ],
        [
            'id' => 'poison_arrow',
            'name' => 'Poison Arrow',
            'mana' => 20,
            'dmg_mult' => 1.2,
            'icon' => 'skull',
            'type' => 'single',
            'range' => 4,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'description' => 'A poisoned arrow that deals damage and has a chance to poison the target.',
            'effect' => ['id' => 'poison', 'chance' => 0.6, 'duration' => 3],
        ],
        [
            'id' => 'focused_shot',
            'name' => 'Focused Shot',
            'mana' => 25,
            'dmg_mult' => 1.8,
            'icon' => 'crosshair',
            'type' => 'single',
            'range' => 5,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'description' => 'A precise shot with increased damage and longer range.',
        ],
        [
            'id' => 'piercing_arrow',
            'name' => 'Piercing Arrow',
            'mana' => 30,
            'dmg_mult' => 1.3,
            'icon' => 'arrow-right',
            'type' => 'line',
            'range' => 5,
            'rangeType' => 'line',
            'aoe' => 0,
            'gridVisual' => 'line',
            'description' => 'An arrow that pierces through enemies in a line, hitting multiple targets.',
        ],
        [
            'id' => 'multishot',
            'name' => 'Multishot',
            'mana' => 35,
            'dmg_mult' => 0.8,
            'hits' => 3,
            'icon' => 'target',
            'type' => 'aoe',
            'range' => 4,
            'rangeType' => 'area',
            'aoe' => 1,
            'gridVisual' => 'aoe_small',
            'description' => 'Fires multiple arrows at nearby targets, hitting up to 3 enemies.',
        ],
        [
            'id' => 'hunters_focus',
            'name' => 'Hunter\'s Focus',
            'mana' => 30,
            'dmg_mult' => 0,
            'icon' => 'eye',
            'type' => 'self',
            'description' => 'Increases DEX, accuracy, crit chance and damage dealt for 3 turns.',
            'buff' => [
                'stats' => ['dex' => 15],
                'critBonus' => 0.15,
                'damageDealt' => 1.3,
                'duration' => 3
            ],
        ],
        [
            'id' => 'tactical_retreat',
            'name' => 'Tactical Retreat',
            'mana' => 25,
            'dmg_mult' => 1.0,
            'icon' => 'arrow-left-right',
            'type' => 'single',
            'range' => 4,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'description' => 'Shoots an arrow and gains increased movement range for this turn.',
            'buff' => [
                'moveRangeBonus' => 2,
                'duration' => 1
            ],
        ],
        [
            'id' => 'rain_of_arrows',
            'name' => 'Rain of Arrows',
            'mana' => 50,
            'dmg_mult' => 1.0,
            'icon' => 'droplets',
            'type' => 'aoe',
            'range' => 5,
            'rangeType' => 'area',
            'aoe' => 2,
            'gridVisual' => 'aoe_medium',
            'description' => 'Fires a volley of arrows at a target area, hitting all enemies within range.',
        ],
        [
            'id' => 'crippling_shot',
            'name' => 'Crippling Shot',
            'mana' => 40,
            'dmg_mult' => 1.5,
            'icon' => 'arrow-down',
            'type' => 'single',
            'range' => 4,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'description' => 'A powerful shot that deals damage and slows the target.',
            'effect' => ['id' => 'slow', 'chance' => 1.0, 'duration' => 2],
        ],
        [
            'id' => 'deadly_aim',
            'name' => 'Deadly Aim',
            'mana' => 55,
            'dmg_mult' => 2.5,
            'critBonus' => 0.5,
            'icon' => 'target',
            'type' => 'single',
            'range' => 5,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'ranged',
            'ultimate' => true,
            'description' => 'ULTIMATE: A perfectly aimed shot with massive damage and high critical chance.',
        ],
    ],
];



