<?php

return [
    'id' => 'beast_tamer',
    'type' => 'class',
    'is_player' => true,
    'name' => 'Beast Tamer',
    'display_name' => 'Beast Tamer',
    'role' => 'Summoner',
    'element' => 'neutral',
    'desc' => 'A master of beasts who commands the wild. They form deep bonds with creatures of nature, summoning them to fight alongside in battle.',
    'base_level' => 1,
    'images' => [
        'default' => 'assets/entities/beast_tamer/avatar.webp',
    ],
    'animations' => [
        'base' => 'entities',
        'types' => ['idle', 'walk', 'atack'],
        'idle'  => ['animationFPS' => 12, 'animationScale' => 1.5, 'animationOffsetX' => 1, 'animationOffsetXWhenFacingRight' => -1,  'animationOffsetY' => 32],
        'walk'  => ['animationFPS' => 9,  'animationScale' => 1.5, 'animationOffsetX' => -7, 'animationOffsetXWhenFacingRight' => 7,  'animationOffsetY' => 38],
        'atack' => ['animationFPS' => 12, 'animationScale' => 2.0, 'animationOffsetX' => -10, 'animationOffsetXWhenFacingRight' => 10, 'animationOffsetY' => 40],
    ],
    'sounds' => [
        'weapon' => 'whip',
        'skill_start' => ['howling_wolf'], // Uivo para skills de summon
        'summon_cast' => ['howling_wolf'], // Som específico para invocação
        'hit' => ['whip', 'staff_hit', 'staff_hit2'],
        'attack_prepare' => ['whip'],
        'death' => ['hero_death'],
        'damage_taken' => ['damage_taken1'],
        'buff_apply' => ['buff_apply1', 'buff_apply2'],
        'debuff_apply' => ['debuff_apply'],
    ],
    'attributes' => [
        'str' => 7,
        'agi' => 10,
        'vit' => 8,
        'int' => 12,
        'dex' => 11,
        'luk' => 7,
    ],
    'maxHp' => 75,
    'maxSp' => 130,
    'attack' => 8,
    'defense' => 4,
    'moveRange' => 3,
    'attackRange' => 1,
    'scale' => 1.6,
    'skills' => [
        [
            'id' => 'summon_wolf',
            'name' => 'Summon Wolf',
            'mana' => 40,
            'dmg_mult' => 0,
            'icon' => 'sparkles',
            'type' => 'summon',
            'range' => 0,
            'rangeType' => 'self',
            'aoe' => 0,
            'gridVisual' => 'self',
            'summonEntity' => 'wolf',
            'description' => 'Invokes a Dire Wolf to fight alongside you. The wolf attacks enemies in melee range.',
        ],
        [
            'id' => 'summon_hawk',
            'name' => 'Summon Hawk',
            'mana' => 35,
            'dmg_mult' => 0,
            'icon' => 'sparkles',
            'type' => 'summon',
            'range' => 0,
            'rangeType' => 'self',
            'aoe' => 0,
            'gridVisual' => 'self',
            'summonEntity' => 'hawk',
            'description' => 'Invokes a Hawk to fight alongside you. The hawk attacks enemies from a distance.',
        ],
        [
            'id' => 'pack_leader',
            'name' => 'Pack Leader',
            'mana' => 0,
            'dmg_mult' => 0,
            'icon' => 'crown',
            'type' => 'self',
            'range' => 0,
            'rangeType' => 'self',
            'aoe' => 0,
            'gridVisual' => 'self',
            'description' => 'Passive: Increases damage and speed of all summoned beasts. Automatically applied to all summons.',
            'buff' => [
                'id' => 'pack_leader',
                'name' => 'Pack Leader',
                'icon' => 'crown',
                'damageDealt' => 1.2,
                'duration' => -1, // Permanent until removed
            ],
        ],
        [
            'id' => 'wild_instinct',
            'name' => 'Wild Instinct',
            'mana' => 30,
            'dmg_mult' => 0,
            'icon' => 'eye',
            'type' => 'aoe_heal',
            'range' => 0,
            'rangeType' => 'aoe',
            'aoe' => 0,
            'gridVisual' => 'aoe_heal',
            'description' => 'Increases AGI and DEX of all allies. The wild spirit inspires your party.',
            'buff' => [
                'id' => 'wild_instinct',
                'name' => 'Wild Instinct',
                'icon' => 'eye',
                'stats' => ['agi' => 10, 'dex' => 8],
                'duration' => 3,
            ],
        ],
        [
            'id' => 'intimidating_roar',
            'name' => 'Intimidating Roar',
            'mana' => 25,
            'dmg_mult' => 0,
            'icon' => 'shield',
            'type' => 'aoe',
            'range' => 0,
            'rangeType' => 'aoe',
            'aoe' => 2,
            'gridVisual' => 'aoe_medium',
            'description' => 'A fearsome roar that reduces ATK and DEF of all enemies in the area.',
            'debuff' => [
                'id' => 'intimidated',
                'name' => 'Intimidated',
                'icon' => 'shield',
                'stats' => ['str' => -5, 'def' => -3],
                'duration' => 2,
            ],
        ],
        [
            'id' => 'natures_blessing',
            'name' => 'Nature\'s Blessing',
            'mana' => 35,
            'dmg_mult' => 0,
            'healPct' => 0.25,
            'healMatk' => 0.5,
            'power' => 0,
            'icon' => 'heart',
            'type' => 'aoe_heal',
            'range' => 0,
            'rangeType' => 'aoe',
            'aoe' => 0,
            'gridVisual' => 'aoe_heal',
            'description' => 'Heals all allies for 25% of their max HP plus bonus from INT/MATK. The power of nature restores your party.',
        ],
    ],
];
