<?php

return [
    'id' => 'swordsman',
    'type' => 'class',
    'is_player' => true,
    'name' => 'Swordsman',
    'display_name' => 'Swordsman',
    'role' => 'Warrior',
    'element' => 'neutral',
    'desc' => 'A disciplined warrior trained in one-handed combat and military tactics. Masters of sword and shield, they excel at both offense and defense, making them reliable front-line fighters.',
    'base_level' => 1,
    'images' => [
        'default' => 'assets/entities/swordsman/avatar.webp',
        'male' => 'assets/entities/swordsman/avatar.webp',
        'female' => 'assets/entities/swordsman/avatar.webp',
    ],
    'animations' => [
        'base' => 'entities',
        'types' => ['idle', 'walk', 'atack'],
        'idle'  => ['animationFPS' => 15,  'animationScale' => 1.4, 'animationOffsetX' => 6,  'animationOffsetXWhenFacingRight' => -6, 'animationOffsetY' => 34],
        'walk'  => ['animationFPS' => 14.5, 'animationScale' => 2,   'animationOffsetX' => 2,  'animationOffsetXWhenFacingRight' => -2, 'animationOffsetY' => 34],
        'atack' => ['animationFPS' => 13,  'animationScale' => 3.6, 'animationOffsetX' => -2, 'animationOffsetXWhenFacingRight' => 2,  'animationOffsetY' => 70],
    ],
    'sounds' => [
        'weapon' => 'sword',
        'skill_start' => ['swordman_skill_start1', 'swordman_skill_start2', 'swordman_skill_start3'],
        'hit' => ['sword1', 'sword2', 'sword3', 'sword4'],
        'attack_prepare' => ['sword1', 'sword2', 'sword3'],
        'death' => ['hero_death'],
        'damage_taken' => ['damage_taken1', 'damage_taken2', 'damage_taken3', 'damage_taken4'],
        'crit' => ['critical'],
        'buff_apply' => ['buff_apply1', 'buff_apply2', 'buff_apply3'],
        'debuff_apply' => ['debuff_apply'],
        'parry' => ['parry1', 'parry2'],
    ],
    'growth' => [
        'hp_base_per_level' => 100,
        'hp_vit_mult'       => 20,
        'sp_base_per_level' => 10,
        'sp_int_mult'       => 5,
        'atk_base'          => 50,
        'atk_str_mult'      => 2,
        'atk_lvl_mult'      => 1.5,
        'matk_base'         => 30,
        'matk_int_mult'     => 2,
        'matk_lvl_mult'     => 1.2,
    ],
    'attributes' => [
        'str' => 12,
        'agi' => 8,
        'vit' => 10,
        'int' => 15,
        'dex' => 8,
        'luk' => 5,
    ],
    'maxHp' => 130,
    'maxSp' => 250,
    'attack' => 14,
    'defense' => 10,
    'moveRange' => 4,
    'attackRange' => 1,
    'scale' => 1.7,
    'skills' => [
        [
            'id' => 'quick_slash',
            'unlock_level' => 1,
            'name' => 'Quick Slash',
            'mana' => 5,
            'dmg_mult' => 1.0,
            'icon' => 'sword',
            'type' => 'single',
            'range' => 1,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'melee',
            'description' => 'Basic physical attack against a single target.',
        ],
        [
            'id' => 'guarded_strike',
            'unlock_level' => 2,
            'name' => 'Guarded Strike',
            'mana' => 15,
            'dmg_mult' => 1.2,
            'icon' => 'shield',
            'type' => 'single',
            'description' => 'Moderate physical attack. 15% Stun chance.',
            'effect' => ['id' => 'stun', 'chance' => 0.15, 'duration' => 1],
        ],
        [
            'id' => 'parry_stance',
            'unlock_level' => 3,
            'name' => 'Parry Stance',
            'mana' => 15,
            'dmg_mult' => 0,
            'icon' => 'shield',
            'type' => 'ally',
            'description' => 'Increases parry chance to 30% for 1 turn.',
            'buff' => [
                'parryChance' => 0.3,
                'duration' => 1
            ],
        ],
        [
            'id' => 'heavy_slash',
            'unlock_level' => 5,
            'name' => 'Heavy Slash',
            'mana' => 20,
            'dmg_mult' => 2.0,
            'hits' => 2,
            'icon' => 'sword',
            'type' => 'single',
            'range' => 1,
            'rangeType' => 'single',
            'aoe' => 0,
            'gridVisual' => 'melee',
            'description' => 'Strong physical attack that strikes twice.',
        ],
        [
            'id' => 'shield_bash',
            'unlock_level' => 8,
            'name' => 'Shield Bash',
            'mana' => 25,
            'dmg_mult' => 1.3,
            'icon' => 'shield',
            'type' => 'single',
            'description' => 'Moderate attack. 50% Stun chance.',
            'effect' => ['id' => 'stun', 'chance' => 0.5, 'duration' => 1],
        ],
        [
            'id' => 'taunting_shout',
            'unlock_level' => 10,
            'name' => 'Taunting Shout',
            'mana' => 10,
            'dmg_mult' => 0,
            'icon' => 'speaker',
            'type' => 'self',
            'description' => 'Provokes enemies to target you (80% chance).',
            'buff' => [
                'tauntChance' => 0.8,
                'duration' => 1
            ],
        ],
        [
            'id' => 'cleave',
            'unlock_level' => 14,
            'name' => 'Cleave',
            'mana' => 30,
            'dmg_mult' => 0.8,
            'icon' => 'target',
            'type' => 'aoe',
            'range' => 1,
            'rangeType' => 'aoe',
            'aoe' => 1,
            'gridVisual' => 'aoe_small',
            'description' => 'Physical attack that hits all enemies.',
        ],
        [
            'id' => 'defensive_wall',
            'unlock_level' => 18,
            'name' => 'Defensive Wall',
            'mana' => 30,
            'dmg_mult' => 0,
            'icon' => 'shield-check',
            'type' => 'ally',
            'description' => 'Reduces damage taken by 50% for 2 turns.',
            'buff' => [
                'damageTaken' => 0.5,
                'duration' => 2
            ],
        ],
        [
            'id' => 'crushing_blow',
            'unlock_level' => 22,
            'name' => 'Crushing Blow',
            'mana' => 25,
            'dmg_mult' => 1.6,
            'icon' => 'hammer',
            'type' => 'single',
            'description' => 'Heavy attack. 30% Bleed chance.',
            'effect' => ['id' => 'bleed', 'chance' => 0.3, 'duration' => 2],
        ],
        [
            'id' => 'battle_focus',
            'unlock_level' => 30,
            'name' => 'Battle Focus',
            'mana' => 40,
            'dmg_mult' => 0,
            'icon' => 'zap',
            'type' => 'ally',
            'description' => 'Increases target STR, DEX and damage dealt by 50% for 3 turns.',
            'buff' => [
                'stats' => ['str' => 20, 'dex' => 15],
                'damageDealt' => 1.5,
                'duration' => 3
            ],
        ],
        [
            'id' => 'relentless_strike',
            'unlock_level' => 35,
            'name' => 'Relentless Strike',
            'mana' => 35,
            'dmg_mult' => 0.7,
            'hits' => 2,
            'icon' => 'sword',
            'type' => 'single',
            'description' => 'Powerful attack that hits the target twice.',
        ],
        [
            'id' => 'champions_slash',
            'unlock_level' => 50,
            'name' => 'Champion\'s Slash',
            'mana' => 60,
            'dmg_mult' => 3.0,
            'hits' => 3,
            'icon' => 'crown',
            'type' => 'single',
            'range' => 3,
            'rangeType' => 'line',
            'aoe' => 0,
            'gridVisual' => 'line',
            'ultimate' => true,
            'description' => 'ULTIMATE: Devastating 3-hit combo with Stun/Bleed chance.',
            'effects' => [
                ['id' => 'stun', 'chance' => 0.4, 'duration' => 1],
                ['id' => 'bleed', 'chance' => 0.4, 'duration' => 2]
            ],
        ],
        [
            'id' => 'life_steal',
            'unlock_level' => 60,
            'name' => 'Life Steal',
            'mana' => 55,
            'dmg_mult' => 1.1,
            'stealPercent' => 0.4,
            'icon' => 'heart',
            'type' => 'single',
            'description' => 'Deals damage and steals 40% of damage dealt as HP. Great for sustain.',
        ],
        [
            'id' => 'berserk_mode',
            'unlock_level' => 70,
            'name' => 'Berserk Mode',
            'mana' => 65,
            'dmg_mult' => 0,
            'icon' => 'zap',
            'type' => 'self',
            'description' => 'Increases ATK by 100% but reduces DEF by 50% for 3 turns. High risk, high reward.',
            'buff' => [
                'id' => 'berserk_mode',
                'atkBonus' => 1.0,
                'defPenalty' => -0.5,
                'duration' => 3
            ],
        ],
    ],
];



